require('user.options')
require('user.keymaps')
require('user.autocommands')
require('user.plugins')
require('user.eviline')
require('user.lspconfig')
require('user.nvim-tree')
require('user.bufferline')
require('user.colorscheme')
require('user.treesitter')
require('user.gitsigns')
require('user.commont')
require('user.indent-blankline')

