# Cross-platform btop configuration for macOS and Linux.

color_theme = "Default"
theme_background = false
truecolor = true
force_tty = false

presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
vim_keys = true
rounded_corners = true
terminal_sync = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000

proc_sorting = "cpu lazy"
proc_tree = false
proc_colors = true
proc_gradient = true
proc_mem_bytes = true
proc_cpu_graphs = true
proc_info_smaps = false
proc_filter_kernel = false

show_gpu_info = "Auto"
show_uptime = true
show_cpu_watts = false
check_temp = true
show_coretemp = true
temp_scale = "celsius"
show_cpu_freq = true
clock_format = "%X"

mem_graphs = true
show_swap = true
swap_disk = false
show_disks = true
only_physical = true
use_fstab = false
show_io_stat = true

net_auto = true
net_sync = true
show_battery = true
show_battery_watts = true

log_level = "WARNING"
save_config_on_exit = false
shown_gpus = "nvidia amd intel apple"
